### PR TITLE
Implement clap and handle args

### PR DESCRIPTION
**Pull request by Kitt3120**
- Add clap crate
- Handle args
- Handle stdin

### CODE REVIEW

**Comment by Kitt3120** [comment]
@Murasko

**Comment by Kitt3120** [comment]
@Murasko

**Comment by Kitt3120** [comment]
@Murasko

**Comment by Murasko** [comment]
@Kitt3120 lgtm

**Comment by Kitt3120** [comment]
@Murasko ❤️😗

**Pull request merged**
